name: "viralverify"
description: "viralVerify classifies contigs (output of metaviralSPAdes or other assemblers) as viral, non-viral or uncertain, based on gene content. Also for non-viral contigs it can optionally provide plasmid/non-plasmid classification."
keywords:
  - viral
  - non-viral
  - contig
  - classification

tools:
  - "viralverify":
      description: "viral contig verification tool"
      homepage: "https://github.com/ablab/viralVerify"
      documentation: "https://anaconda.org/bioconda/viralverify"
      tool_dev_url: "https://github.com/ablab/viralVerify"
      doi: ""
      licence: "['GPL v3']"

input:

  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA file
      pattern: "*.fasta"

  - hmm:
      type: file
      description: Path to HMM database
      pattern: "*.hmm"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

  - csv:
     type: file
     description: File containing comma-separated table
     pattern: "*.csv"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@mariguilardi"
